package frc.robot.utils.simulation;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.configs.Slot0Configs;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.units.measure.Mass;
import edu.wpi.first.units.measure.MomentOfInertia;
import edu.wpi.first.units.measure.Voltage;
import frc.robot.generated.TunerConstants;

public final class SimSwerveConstants {
    // TODO: update constants to what's physically on the robot
    public static final Mass ROBOT_MASS = Pounds.of(115);
    public static final Distance BUMPER_LENGTH_X = Inches.of(30);
    public static final Distance BUMPER_LENGTH_Y = Inches.of(30);
    public static final double WHEEL_COF = 1.2;
    public static final DCMotor DRIVE_MOTOR_WHEEL = DCMotor.getKrakenX60(1);
    public static final DCMotor STEER_MOTOR_WHEEL = DCMotor.getKrakenX60(1);

    // Use values from generated TunerConstants where available to avoid duplicate
    // definitions. TunerConstants is generated by the Tuner tool and must not be
    // edited; prefer those values for module/drivetrain tuning parameters.
    public static final Slot0Configs STEER_MOTOR_GAINS = TunerConstants.FrontLeft.SteerMotorGains;
    public static final double STEER_MOTOR_GEAR_RATIO =
        TunerConstants.FrontLeft.SteerMotorGearRatio;
    public static final Voltage DRIVE_FRICTION_VOLTAGE =
        Volts.of(TunerConstants.FrontLeft.DriveFrictionVoltage);
    public static final Voltage STEER_FRICTION_VOLTAGE =
        Volts.of(TunerConstants.FrontLeft.SteerFrictionVoltage);
    public static final MomentOfInertia STEER_INERTIA =
        KilogramSquareMeters.of(TunerConstants.FrontLeft.SteerInertia);
  }
